all:
  hosts:
    192.168.79.136:
      ansible_user: rommel
      ansible_ssh_pass: 'rommel'
      ansible_become: yes
      ansible_become_user: root
      ansible_become_pass: 'rommel'  # Mot de passe sudo



