all:
  hosts:
    192.168.79.136:
      ansible_user: rommel
      ansible_ssh_pass: rommel
      ansible_ssh_private_key_file: ""
      ansible_become: yes
      ansible_become_pass: rommel
      ansible_python_interpreter: /usr/bin/python3
