all:
  hosts:
    192.168.79.136:
      ansible_user: rommel
      ansible_password: rommel
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      ansible_python_interpreter: /usr/libexec/platform-python
