---
- name: Install and configure NGINX
  hosts: all
  become: yes
  tasks:
    - name: Ensure NGINX is installed
      package:
        name: nginx
        state: present

    - name: Start NGINX service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Validate NGINX configuration
      command: nginx -t

