- name: Validate NGINX configuration
  command: nginx -t
  register: nginx_config_test
  ignore_errors: yes

- name: Fail if NGINX configuration is invalid
  fail:
    msg: "NGINX configuration is invalid. Check the logs and correct the errors."
  when: nginx_config_test.rc != 0

- name: Ensure NGINX is running
  service:
    name: nginx
    state: started
