
- name: Install and configure NGINX
  hosts: all
  become: yes
  vars:
    index_file_path: /usr/share/nginx/html/index.html
  tasks:
    - name: Install NGINX
      ansible.builtin.yum:
        name: nginx
        state: present

    - name: Ensure NGINX is running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Create index.html with the value of mavariable
      ansible.builtin.copy:
        dest: "{{ index_file_path }}"
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>Welcome</title>
          </head>
          <body>
              <h1>Variable: {{ mavariable }}</h1>
          </body>
          </html>
      vars:
        mavariable: "{{ lookup('env', 'MAVARIABLE') }}"  # Retrieves the value of MAVARIABLE from the environment
